-- ESTADOS DE ORDEN
INSERT INTO ESTADO_ORDEN (ID, NOMBRE) VALUES (1, 'ABIERTA');
INSERT INTO ESTADO_ORDEN (ID, NOMBRE) VALUES (2, 'DIAGNOSTICO');
INSERT INTO ESTADO_ORDEN (ID, NOMBRE) VALUES (3, 'EN_PROCESO');
INSERT INTO ESTADO_ORDEN (ID, NOMBRE) VALUES (4, 'PARA_COBRO');
INSERT INTO ESTADO_ORDEN (ID, NOMBRE) VALUES (5, 'CERRADA');

-- ROLES
INSERT INTO ROL (ID, NOMBRE) VALUES (1, 'ADMIN');
INSERT INTO ROL (ID, NOMBRE) VALUES (2, 'RECEPCION');
INSERT INTO ROL (ID, NOMBRE) VALUES (3, 'MECANICO');
INSERT INTO ROL (ID, NOMBRE) VALUES (4, 'CAJA');

COMMIT;
