DECLARE
  v_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists
  FROM user_tab_cols
  WHERE table_name = 'REPUESTO'
    AND column_name = 'VERSION';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE REPUESTO ADD (VERSION NUMBER(10) DEFAULT 0 NOT NULL)';
  ELSE
    EXECUTE IMMEDIATE 'UPDATE REPUESTO SET VERSION = 0 WHERE VERSION IS NULL';
    EXECUTE IMMEDIATE 'ALTER TABLE REPUESTO MODIFY (VERSION DEFAULT 0 NOT NULL)';
  END IF;
END;
/
